aliyun_oss:
    end_point: ""
    access_key_id: yourAccessKeyId
    access_key_secret: yourAccessKeySecret
    bucket_name: yourBucketName
    bucket_url: yourBucketUrl
    base_path: yourBasePath
auto_code:
    server:
    server_model: /model/%s
    server_router: /router/%s
    server_api: /api/%s
    server_plug: /plugin/%s
    server_initialize: /initialize
    root: D:\jelly\GoLearn\gin-web
    web: /web/src
    web_table: /view
    server_service: /service/%s
    server_request: /model/%s/request/
    web_api: /api
    web_form: /view
aws_s3:
    bucket: ""
    region: ""
    end_point: ""
    secret_id: ""
    secret_key: ""
    base_url: ""
    path_prefix: ""
    s3_force_path_style: false
    disable_ssl: false
captcha:
    key_long: 6
    img_width: 240
    img_height: 80
    open_captcha: 0
    open_captcha_time_out: 0
cors:
    mode: strict-whitelist
    white_list: []
db_list:
    - type: ""
      alias_name: ""
      prefix: ""
      port: ""
      config: ""
      db_name: ""
      user_name: ""
      password: ""
      path: ""
      engine: ""
      log_mode: ""
      max_idle_conns: 0
      max_open_conns: 0
      singular: false
      log_zap: false
      disable: true
disk_list: []
email:
    to: xxx@qq.com
    from: ""
    host: smtp.163.com
    secret: xxx
    nick_name: ""
    port: 465
    is_ssl: false
huawei_obs:
    path: ""
    bucket: ""
    end_point: ""
    access_key: ""
    secret_key: ""
jwt:
    signing_key: 3d5d264d-09cf-4ff1-b909-323904f7bbef
    expires_time: 7d
    buffer_time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store_path: uploads/file
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth_source: ""
    min_pool_size: 0
    max_pool_size: 100
    socket_timeout_ms: 0
    connect_timeout_ms: 0
    is_zap: false
    hosts:
        - host: ""
          port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db_name: ""
    user_name: ""
    password: ""
    path: ""
    engine: ""
    log_mode: ""
    max_idle_conns: 0
    max_open_conns: 0
    singular: false
    log_zap: false
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: gin_admin
    user_name: root
    password: "123456"
    path: 127.0.0.1
    engine: ""
    log_mode: error
    max_idle_conns: 10
    max_open_conns: 100
    singular: false
    log_zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db_name: ""
    user_name: ""
    password: ""
    path: ""
    engine: ""
    log_mode: ""
    max_idle_conns: 0
    max_open_conns: 0
    singular: false
    log_zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db_name: ""
    user_name: ""
    password: ""
    path: ""
    engine: ""
    log_mode: ""
    max_idle_conns: 0
    max_open_conns: 0
    singular: false
    log_zap: false
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img_path: ""
    access_key: ""
    secret_key: ""
    use_https: false
    use_cdn_domains: false
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    use_cluster: false
    cluster_addrs: []
sqlite:
    prefix: ""
    port: ""
    config: ""
    db_name: ""
    user_name: ""
    password: ""
    path: ""
    engine: ""
    log_mode: ""
    max_idle_conns: 0
    max_open_conns: 0
    singular: false
    log_zap: false
system:
    db_type: mysql
    oss-type: ""
    router_prefix: ""
    addr: 8888
    limit_count_ip: 0
    limit_time_ip: 0
    use_multipoint: false
    use_redis: false
    use_mongo: false
tencent_cos:
    bucket: xxxxx_10005608
    region: ap_shanghai
    secret_id: your_secret_id
    secret_key: your_secret_key
    base_url: https://gin.vue.admin
    path_prefix: github.com/flipped_aurora/gin-vue-admin/server
zap:
    level: info
    prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
    format: console
    director: log
    encode_level: LowercaseColorLevelEncoder
    stacktrace_key: stacktrace
    show_line: true
    log_in_console: true
